# Generated by Django 4.1.5 on 2023-01-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
                ('logo', models.ImageField(default='comingsoon.png', upload_to='skills/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
                'ordering': ['-name'],
            },
        ),
    ]
