# Generated by Django 4.1.5 on 2023-01-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
