# Generated by Django 4.1.5 on 2023-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(upload_to='skills/', verbose_name='Logo'),
        ),
    ]
