# Generated by Django 4.1.5 on 2023-01-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/icons', verbose_name='Icono'),
        ),
    ]
