# Generated by Django 4.1.5 on 2023-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
