# Generated by Django 4.1.5 on 2023-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
